// <auto-generated />
using System;
using ChamCongService.ChamCongService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChamCongService.Migrations
{
    [DbContext(typeof(ChamCongDbContext))]
    [Migration("20260515130907_RenamePhieuChamCongToPhieuDangKyNghi")]
    partial class RenamePhieuChamCongToPhieuDangKyNghi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChamCongService.Domain.Entity.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPresent")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("ChamCongService.Domain.Entity.LoaiChamCong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<double>("HeSo")
                        .HasColumnType("double precision");

                    b.Property<int>("HinhThuc")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LoaiChamCongs");
                });

            modelBuilder.Entity("ChamCongService.Domain.Entity.PhieuDangKyNghi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoaiChamCongId")
                        .HasColumnType("uuid");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("NgayNghi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LoaiChamCongId");

                    b.ToTable("PhieuDangKyNghis");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PhieuDangKyNghi");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ChamCongService.Domain.Entity.PhieuDangKyNghiTheoBuoi", b =>
                {
                    b.HasBaseType("ChamCongService.Domain.Entity.PhieuDangKyNghi");

                    b.Property<int>("LoaiBuoi")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("PhieuDangKyNghiTheoBuoi");
                });

            modelBuilder.Entity("ChamCongService.Domain.Entity.PhieuDangKyNghiTheoGio", b =>
                {
                    b.HasBaseType("ChamCongService.Domain.Entity.PhieuDangKyNghi");

                    b.Property<TimeSpan>("DenGio")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TuGio")
                        .HasColumnType("interval");

                    b.HasDiscriminator().HasValue("PhieuDangKyNghiTheoGio");
                });

            modelBuilder.Entity("ChamCongService.Domain.Entity.PhieuDangKyNghiTheoNgay", b =>
                {
                    b.HasBaseType("ChamCongService.Domain.Entity.PhieuDangKyNghi");

                    b.HasDiscriminator().HasValue("PhieuDangKyNghiTheoNgay");
                });

            modelBuilder.Entity("ChamCongService.Domain.Entity.PhieuDangKyNghi", b =>
                {
                    b.HasOne("ChamCongService.Domain.Entity.LoaiChamCong", "LoaiChamCong")
                        .WithMany()
                        .HasForeignKey("LoaiChamCongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiChamCong");
                });
#pragma warning restore 612, 618
        }
    }
}
