// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TinhLuongService.Data;

#nullable disable

namespace TinhLuongService.Migrations
{
    [DbContext(typeof(TinhLuongDbContext))]
    [Migration("20260515120351_UpdateKyTinhLuong")]
    partial class UpdateKyTinhLuong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TinhLuongService.Domain.Entities.KyTinhLuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("ChotTinhLuong")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("MaKy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("KyTinhLuongs");
                });

            modelBuilder.Entity("TinhLuongService.Domain.Entities.NhanVienTinhLuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("KyTinhLuongId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("LuongCoBan")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LuongThucLanh")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Phat")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhuCap")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Thue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Thuong")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TongLuong")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KyTinhLuongId");

                    b.ToTable("NhanVienTinhLuongs");
                });

            modelBuilder.Entity("TinhLuongService.Domain.Entities.NhanVienTinhLuong", b =>
                {
                    b.HasOne("TinhLuongService.Domain.Entities.KyTinhLuong", null)
                        .WithMany("NhanVienTinhLuongs")
                        .HasForeignKey("KyTinhLuongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TinhLuongService.Domain.Entities.KyTinhLuong", b =>
                {
                    b.Navigation("NhanVienTinhLuongs");
                });
#pragma warning restore 612, 618
        }
    }
}
