// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuyetDinhService.QuyetDinhService.Infrastructure.Data;

#nullable disable

namespace QuyetDinhService.Migrations
{
    [DbContext(typeof(QuyetDinhDbContext))]
    [Migration("20260513131627_AddQuyetDinhNangLuong")]
    partial class AddQuyetDinhNangLuong
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuyetDinhService.Models.QuyetDinh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("LoaiQuyetDinh")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NhanVienId")
                        .HasColumnType("integer");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("QuyetDinh", (string)null);
                });

            modelBuilder.Entity("QuyetDinhService.Models.QuyetDinhNangLuong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<decimal>("LuongCu")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LuongMoi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NhanVienId")
                        .HasColumnType("uuid");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("QuyetDinhNangLuong", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
