// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuyetDinhService.QuyetDinhService.Infrastructure.Data;

#nullable disable

namespace QuyetDinhService.Migrations
{
    [DbContext(typeof(QuyetDinhDbContext))]
    partial class QuyetDinhDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuyetDinhService.Domain.Entities.QuyetDinhBoNhiem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChucVuCu")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChucVuMoi")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PhuCapCu")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PhuCapMoi")
                        .HasColumnType("numeric");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuyetDinhBoNhiems");
                });

            modelBuilder.Entity("QuyetDinhService.Domain.Entities.QuyetDinhNangLuong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("LuongCoBanCu")
                        .HasColumnType("numeric");

                    b.Property<decimal>("LuongCoBanMoi")
                        .HasColumnType("numeric");

                    b.Property<Guid>("MaNhanVien")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NgayHieuLuc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NgayQuyetDinh")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SoQuyetDinh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuyetDinhNangLuongs");
                });
#pragma warning restore 612, 618
        }
    }
}
